services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: finguard-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: finguard-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - ./scripts:/scripts:ro
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 12

  flink-jobmanager:
    image: flink:1.19.1-scala_2.12-java17
    container_name: finguard-flink-jobmanager
    command: jobmanager
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        parallelism.default: 2
        taskmanager.numberOfTaskSlots: 4
        execution.checkpointing.interval: 60s
    volumes:
      - ./flink-job/target:/opt/flink/usrlib
      - ./data:/opt/finguard/data

  flink-taskmanager:
    image: flink:1.19.1-scala_2.12-java17
    container_name: finguard-flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 4
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        parallelism.default: 2
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./flink-job/target:/opt/flink/usrlib
      - ./data:/opt/finguard/data

  postgres:
    image: postgres:16-alpine
    container_name: finguard-postgres
    profiles: ["db"]
    environment:
      POSTGRES_USER: finguard
      POSTGRES_PASSWORD: finguard
      POSTGRES_DB: finguard
    ports:
      - "5432:5432"
    volumes:
      - finguard_postgres:/var/lib/postgresql/data

volumes:
  finguard_postgres:
